services:
  # Service API Backend (FastAPI)
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: recoMangaTion-api
    ports:
      - "8001:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql+psycopg://api:api@db:5432/db_anilist
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 35s
    networks:
      - recoMangaTion-network
      - monitoring 

  # Service Frontend Web
  web:
    build:
      context: ./web
    ports:
      - "5174:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8001
    depends_on:
      - api
    networks:
      - recoMangaTion-network

  
  # Service Database (PostgreSQL)
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api
      POSTGRES_DB: db_anilist
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U api -d db_anilist"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
    - recoMangaTion-network 

  # Prometheus : 
  prometheus:
    image: prom/prometheus
    container_name: prometheus-container
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9092:9090
    restart: unless-stopped
    networks:
      - monitoring
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    depends_on:
      - api

  # Grafana :
  grafana:
    image: grafana/grafana
    container_name: grafana-container
    ports:
      - 3002:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    networks:
      - monitoring
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
  
  #MLFlow
  mlflow:
    image: python:3.11-slim
    container_name: mlflow-server
    working_dir: /app
    volumes:
      - ./:/app
      - mlflow_data:/mlflow
    command: >
      sh -lc "
      pip install -q 'mlflow>=2.9.0' &&
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:////mlflow/mlflow.db
      --default-artifact-root mlflow-artifacts:/
      --artifacts-destination /mlflow/artifacts
      --serve-artifacts
      "
    ports:
      - "5001:5000"

networks:
  recoMangaTion-network:
    driver: bridge
  monitoring:
    driver: bridge

volumes:
  prom_data:
  grafana_data:
  pgdata:
  mlflow_data:
