metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"

replication_mode = "none"

rpc_bind_addr = "[::]:3902"
rpc_public_addr = "garage:3902"

[s3_api]
s3_region = "us-east-1"
api_bind_addr = "[::]:3900"

[admin_api]
api_bind_addr = "[::]:3901"